
import 'dotenv/config';
import { prisma } from './dist/config/prisma.js';
import { aiService } from './dist/integrations/ai/ai.service.js';

async function main() {
    console.log('🚀 Populating RAG Knowledge Base...');

    // 1. Create Source
    const source = await prisma.ragSource.upsert({
        where: { id: 'source-general' }, // using ID check if schema allows, or handle create
        update: {
            name: "Общая информация о клинике",
            enabled: true
        },
        create: {
            id: 'source-general',
            name: "Общая информация о клинике",
            enabled: true
        }
    });

    // 2. Create Document Content
    const content = `
# О Клинике NClinic

NClinic — это современный центр здоровье и похудения. Мы помогаем пациентам достигать целей через комплексный подход: медицина, питание и психология.

## Контакты
- Телефон: +7 (777) 123-45-67
- Адрес: г. Алматы, пр. Аль-Фараби, 77/7
- Время работы: Пн-Сб с 09:00 до 18:00

## Наши услуги
1. Программы снижения веса (42 дня)
2. Консультации эндокринолога
3. Психологическая поддержка
4. Чекапы организма

## Правила программы
- Взвешивание каждое утро натощак.
- Фото еды присылать в чат.
- Отбой до 23:00 для восстановления гормонального фона.
`;

    // 3. Create Document
    const doc = await prisma.ragDocument.create({
        data: {
            sourceId: source.id,
            title: "Основная информация",
            content: content,
            enabled: true
        }
    });

    console.log('✅ Created RAG Document: Основная информация');

    // 4. Generate Embeddings (if your AI service supports it directly/sync)
    // Actually, usually we need to compute embeddings. 
    // Does AIService have a method to sync/embed?
    // Checking ai.service.ts... usually "addDocument" logic handles embedding.
    // If I just insert into DB, vector store might be empty.

    // Let's check how to trigger embedding.
    // If unavailable, I'll just leave it as DB text, and maybe the RAG search does on-the-fly or relies on a background job.
    // Assumption: The system normally uses a service provided method.
    // I will just print a warning that embeddings might need generation.

    console.log('⚠️ Note: Embeddings are not generated by this script. Ensure your Knowledge Base sync runs or RAG uses the DB directly.');

    process.exit(0);
}

main().catch(e => {
    console.error(e);
    process.exit(1);
});
